services:
  dndtools:
    build: ../dndtools
    ports:
      - "8000:8000"

  jeeves:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DNDTOOLS_URL=http://dndtools:8000
    depends_on:
      - dndtools
